spring:
  config:
    import:
      - "configserver:${CONFIGSERVER_SCHEME:http}://${CONFIGSERVER_HOST:configserver}:${CONFIGSERVER_PORT:8888}/${CONFIGSERVER_PREFIX:config}"
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}
